# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wrm6QkBrun0kYzkd30K14oaCPn3VARmr

# Testing the model
"""

import numpy as np 
import pandas as pd 

from sklearn import preprocessing
from sklearn.model_selection import train_test_split

import keras

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import xgboost

from sklearn.model_selection import RandomizedSearchCV

df_test = pd.read_csv('/content/testingdata.csv' , names = range(45))              #testing data          # please paste testing data path between Single Quotation Marks (‘ ’) like'.....Paste Here.....' 
                     #'....Testing data path..' 
df_test

df_test_np = df_test.values            # converting to ndarray

"""# Loading model"""

from joblib import Parallel, delayed
import joblib

clf_from_joblib = joblib.load('Multiple_Regression_Topcoder.pkl')                           # loading model           #if it doesn't work then paste the  Multiple_Regression_Topcoder.pkl path between Single Quotation Marks (‘ ’) like'.....Paste Here.....'
                               #'.............path.............'

clf_from_joblib.predict(df_test_np)                                                     #prediction

y_prediction= clf_from_joblib.predict(df_test_np)

df_submission = df_test

df_submission[45] = y_prediction

df_submission

df_submission[45] = df_submission[45].astype(float).round(2)

"""# Final Submission"""

df_submission